POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjY2OTNhMDBlMDMzMDAxYmIwNzVmNTVmYSIsImlhdCI6MTcyMDk1MDk2Mn0.-uowzBeqDS1t17kVp6lXwTy7sgR5vdg498RsW4dJTmo

{
  "title": "Test Blog",
  "author": "Test Author",
  "url": "http://testblog.com",
  "likes": 0,
  "id": "5a422b891b54a676234d17fo"
}
