POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3QiLCJpZCI6IjY2OTNhN2MyMGJjZWI0NDk1MDBjZjA4MCIsImlhdCI6MTcyMDk1Mjc5OCwiZXhwIjoxNzIwOTU2Mzk4fQ.mFDWE4tey_ocDhoe3-Wy38WP6c039dCjMoN3XuMjWUk

{
  "title": "Test Blog",
  "author": "Test Author",
  "url": "http://testblog.com",
  "likes": 0,
  "id": "5a422b891b54a676234d17fo"
}
